# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/vector_store.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/vector_store.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protos/vector_store.proto\")\n\rUpsertRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\"\'\n\x0eUpsertResponse\x12\x15\n\rupsert_status\x18\x01 \x01(\t\"2\n\rSearchRequest\x12\x12\n\nquery_text\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\"!\n\x0eSearchResponse\x12\x0f\n\x07results\x18\x01 \x03(\t2c\n\x0bVectorStore\x12)\n\x06Upsert\x12\x0e.UpsertRequest\x1a\x0f.UpsertResponse\x12)\n\x06Search\x12\x0e.SearchRequest\x1a\x0f.SearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.vector_store_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPSERTREQUEST']._serialized_start=29
  _globals['_UPSERTREQUEST']._serialized_end=70
  _globals['_UPSERTRESPONSE']._serialized_start=72
  _globals['_UPSERTRESPONSE']._serialized_end=111
  _globals['_SEARCHREQUEST']._serialized_start=113
  _globals['_SEARCHREQUEST']._serialized_end=163
  _globals['_SEARCHRESPONSE']._serialized_start=165
  _globals['_SEARCHRESPONSE']._serialized_end=198
  _globals['_VECTORSTORE']._serialized_start=200
  _globals['_VECTORSTORE']._serialized_end=299
# @@protoc_insertion_point(module_scope)
